Django_Dr_Bug/Webshop/geekshop/authapp/urls.py
from django.urls import path

import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('register/', authapp.register, name='register'),
    path('login/', authapp.login, name='login'),
    path('edit/<int:pk>/', authapp.EditView.as_view(), name='edit'),
    path('logout/', authapp.logout, name='logout'),
]

Django_Dr_Bug/Webshop/geekshop/basketapp/urls.py
from django.urls import path

from basketapp.views import add, remove, basket, edit

app_name = 'basketapp'

urlpatterns = [
    path('', basket, name='read'),
    path('add/<int:product_pk>/', add, name='add'),
    path('remove/<int:product_pk>/', remove, name='remove'),
    path('edit/<int:pk>/', edit, name='edit'),
]

Django_Dr_Bug/Webshop/geekshop/geekshop/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from mainapp import views as mainapp
from django.conf import settings
from django.conf.urls.static import static
if settings.DEBUG:
    import debug_toolbar

urlpatterns = [
    path('', mainapp.main, name='main'),
    path('products/', include('mainapp.urls', namespace='products')),  #mainapp.products, name='products'
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('contacts/', mainapp.contacts, name='contacts'),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('admin_custom/', include('adminapp.urls', namespace='admin_custom')),
    path('admin/', admin.site.urls),
    path('__debug__/', include(debug_toolbar.urls)),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Django_Dr_Bug/Webshop/geekshop/mainapp/urls.py
from django.urls import path

from mainapp.views import products

app_name = 'mainapp'

urlpatterns = [
    path('', products, name='index'),
    path('category/<int:pk>/', products, name='category'),
]

Django_Dr_Bug/Webshop/geekshop/mainapp/models.py
from django.db import models


class ProductCategory(models.Model):
    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    name = models.CharField(verbose_name="имя категории", max_length=64, unique=True)
    description = models.TextField(verbose_name="описание категории", blank=True)

    def __str__(self):
        return self.name


class Product(models.Model):
    class Meta:
        verbose_name = 'Продукт'
        verbose_name_plural = 'Продукты'

    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE)
    name = models.CharField(verbose_name='имя продукта', max_length=128)
    image = models.ImageField(upload_to='products_images', blank=True)
    short_desc = models.CharField(verbose_name='краткое описание продукта', max_length=60, blank=True)
    description = models.TextField(verbose_name='описание продукта', blank=True)
    price = models.DecimalField(verbose_name='цена продукта', max_digits=8, decimal_places=2, default=0)
    quantity = models.PositiveIntegerField(verbose_name='количество на складе', default=0)
    is_hot = models.BooleanField(verbose_name='горячий продукт', default=False)

    def __str__(self):
        return f"{self.name} ({self.category.name})"

Django_Dr_Bug/Webshop/geekshop/mainapp/views.py
from django.shortcuts import render, get_object_or_404
from .models import Product, ProductCategory

def main(request):
    return render(request, 'mainapp/main.html', {'username': 'doctor bug', 'array': ['e', 'r', 'r', 'o', 'r']})

def products(request, pk=None):
    products = Product.objects.all()

    if pk or pk == 0:
        if pk != 0:
            category = get_object_or_404(ProductCategory, pk=pk)
            products = products.filter(category=category)
        context = {'products': products, 'categories': ProductCategory.objects.all()}
        return render(request, 'mainapp/products.html', context)
    else:
        hot_product = Product.objects.filter(is_hot=True).first()
        context = {'hot_product': hot_product, 'categories': ProductCategory.objects.all()}
        return render(request, 'mainapp/hot_product.html', context)

def contacts(request):
    return render(request, 'mainapp/contacts.html')

Django_Dr_Bug/Webshop/geekshop/mainapp/templates/mainapp/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block title %}
    {% endblock %}

    {% block css %}
        <link rel="stylesheet" href="{% static '/mainapp/css/style.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'mainapp/css/bootstrap.min.css' %}" >
    {% endblock %}
</head>
<body>
    {% include 'mainapp/includes/inc_menu.html' %}

    {% block content %}
    {% endblock %}

    {% block js %}
    {% endblock %}
</body>
</html>

Django_Dr_Bug/Webshop/geekshop/mainapp/templates/mainapp/contacts.html
{% extends 'mainapp/base.html' %}
{% load staticfiles %}

{% block title %}
    <title>Контакты</title>
{% endblock %}

{% block content %}
    <h1>Контакты</h1>
    <p>Оставляйте здесь ваши данные: логин, пароль, паспортные данные,
        ИНН и прочее инфо которые позволят оформить на вас кредит =)</p>
{% endblock %}

Django_Dr_Bug/Webshop/geekshop/mainapp/templates/mainapp/hot_product.html
{% extends 'mainapp/base.html' %}
{% load custom_tags %}

{% block title %}
    <title>Продукты</title>
{% endblock %}

{% block content %}
    <h1>Продукты</h1>
    <div>Количество продуктов в корзине: {{ request.user|basket_total_quantity }}</div>
    <div>Общая стоимость корзины: {{ request.user|basket_total_cost }}</div>
    {% include 'mainapp/includes/inc_category_menu.html' %}
    <div style="display: flex; flex-wrap: wrap;" class="category-products clearfix">
        <div style="margin: 20px" class="block">
              <div class="card" style="width: 18rem;">
                  <img src="/media/{{ hot_product.image }}" class="card-img-top" alt="hot_product">
                  <div class="card-body">
                      <h5 class="card-title">{{ hot_product.name }}</h5>
                      <p class="card-text">{{ hot_product.short_desc }}</p>
                      <h1 style="color: red;">ГОРЯЧЕЕ ПРЕДЛОЖЕНИЕ</h1>
                      <div style="color: red;">На складе осталось 2 товара. Спешите!!!!!!!</div>
                      <a href="{% url 'basket:add' hot_product.pk %}">Добавить в корзину</a>
                      <br>
                      <a href="{% url 'basket:remove' hot_product.pk %}">Удалить из корзины</a>
                  </div>
              </div>
          </div>
    </div>
{% endblock %}

Django_Dr_Bug/Webshop/geekshop/mainapp/templates/mainapp/main.html
{% extends 'mainapp/base.html' %}
{% load staticfiles %}

{% block title %}
    <title>Главная</title>
{% endblock %}

{% block content %}
    <h1 class="red">Главная страница</h1>

    {% if request.user.is_authenticated %}
        <h2>Вас встречает {{request.user.username|title}}!</h2>
    {% else %}
        <p>обычный пользователь, даже не баг</p>
    {% endif %}

    <img src="static/mainapp/img/Doctor_Bug_New_Robot 3.png"/>
{% endblock %}

Django_Dr_Bug/Webshop/geekshop/mainapp/templates/mainapp/products.html
{% extends 'mainapp/base.html' %}
{% load staticfiles %}
{% load custom_tags %}

{% block title %}
    <title>Продукты</title>
{% endblock %}

{% block content %}
    <h1>Категории</h1>
        {% include 'mainapp/includes/inc_category_menu.html' %}
    <div>Количество продуктов в корзине: {{ request.user|basket_total_quantity }}</div>
    <div>Общая стоимость корзины: {{ request.user|basket_total_cost }} руб</div>
    <h1>Продукты</h1>
        <ul>
            {% for product in products %}
                <li>
                    {{ product.name }}
                    <a href="{% url 'basket:add' product.pk %}">Добавить в корзину</a>
                    <a href="{% url 'basket:remove' product.pk %}">Удалить с корзины</a>
                </li>
            {% endfor %}
        </ul>
    <p>Продаем жучков, не дорого!</p>
{% endblock %}