Django_Dr_Bug/Webshop/geekshop/authapp/urls.py
from django.urls import path

import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('register/', authapp.register, name='register'),
    path('login/', authapp.login, name='login'),
    path('edit/<int:pk>/', authapp.EditView.as_view(), name='edit'),
    path('logout/', authapp.logout, name='logout'),
]

Django_Dr_Bug/Webshop/geekshop/basketapp/urls.py
from django.urls import path

from basketapp.views import add, remove, basket, edit

app_name = 'basketapp'

urlpatterns = [
    path('', basket, name='read'),
    path('add/<int:product_pk>/', add, name='add'),
    path('remove/<int:product_pk>/', remove, name='remove'),
    path('edit/<int:pk>/', edit, name='edit'),
]

Django_Dr_Bug/Webshop/geekshop/geekshop/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from mainapp import views as mainapp
from django.conf import settings
from django.conf.urls.static import static
if settings.DEBUG:
    import debug_toolbar

urlpatterns = [
    path('', mainapp.main, name='main'),
    path('products/', include('mainapp.urls', namespace='products')),  #mainapp.products, name='products'
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('contacts/', mainapp.contacts, name='contacts'),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('admin_custom/', include('adminapp.urls', namespace='admin_custom')),
    path('admin/', admin.site.urls),
    path('__debug__/', include(debug_toolbar.urls)),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Django_Dr_Bug/Webshop/geekshop/mainapp/urls.py
from django.urls import path

from mainapp.views import products

app_name = 'mainapp'

urlpatterns = [
    path('', products, name='index'),
    path('category/<int:pk>/', products, name='category'),
]

Django_Dr_Bug/Webshop/geekshop/mainapp/models.py
from django.db import models


class ProductCategory(models.Model):
    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    name = models.CharField(verbose_name="имя категории", max_length=64, unique=True)
    description = models.TextField(verbose_name="описание категории", blank=True)

    def __str__(self):
        return self.name


class Product(models.Model):
    class Meta:
        verbose_name = 'Продукт'
        verbose_name_plural = 'Продукты'

    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE)
    name = models.CharField(verbose_name='имя продукта', max_length=128)
    image = models.ImageField(upload_to='products_images', blank=True)
    short_desc = models.CharField(verbose_name='краткое описание продукта', max_length=60, blank=True)
    description = models.TextField(verbose_name='описание продукта', blank=True)
    price = models.DecimalField(verbose_name='цена продукта', max_digits=8, decimal_places=2, default=0)
    quantity = models.PositiveIntegerField(verbose_name='количество на складе', default=0)
    is_hot = models.BooleanField(verbose_name='горячий продукт', default=False)

    def __str__(self):
        return f"{self.name} ({self.category.name})"

Django_Dr_Bug/Webshop/geekshop/mainapp/views.py
from django.shortcuts import render, get_object_or_404
from .models import Product, ProductCategory

def main(request):
    return render(request, 'mainapp/main.html', {'username': 'doctor bug', 'array': ['e', 'r', 'r', 'o', 'r']})

def products(request, pk=None):
    products = Product.objects.all()

    if pk or pk == 0:
        if pk != 0:
            category = get_object_or_404(ProductCategory, pk=pk)
            products = products.filter(category=category)
        context = {'products': products, 'categories': ProductCategory.objects.all()}
        return render(request, 'mainapp/products.html', context)
    else:
        hot_product = Product.objects.filter(is_hot=True).first()
        context = {'hot_product': hot_product, 'categories': ProductCategory.objects.all()}
        return render(request, 'mainapp/hot_product.html', context)

def contacts(request):
    return render(request, 'mainapp/contacts.html')

Django_Dr_Bug/Webshop/geekshop/mainapp/templates/mainapp/includes/inc_category_menu.html
<a style="margin: 0 10px" href="{% url 'products:category' 0 %}"
   class="{% if request.resolver_match.kwargs.pk == 0 %}
            active
          {% endif %}">
    Все
</a>
{% for category in categories %}
    <a style="margin: 0 10px" href="{% url 'products:category' category.pk %}"
       class="{% if request.resolver_match.kwargs.pk == category.pk %}
                active
              {% endif %}">
        {{ category.name }}
    </a>
{% endfor %}

Django_Dr_Bug/Webshop/geekshop/mainapp/templates/mainapp/includes/inc_menu.html
<ul class="nav nav-tabs">
    <div class="nav-item">
        <a href="{% url 'main' %}"
           class="nav-link {% if request.resolver_match.url_name == 'main' %}
                   active
                  {% endif %} ">
            Главная
        </a>
    </div>
    <div class="nav-item">
        <a href="{% url 'products:index' %}"
           class="nav-link {% if request.resolver_match.url_name == 'products' %}
                   nav-link active
                  {% endif %} ">
            Продукты
        </a>
    </div>
    <div class="nav-item">
        <a href="{% url 'contacts' %}"
           class="nav-link {% if request.resolver_match.url_name == 'contacts' %}
                   nav-link active
                  {% endif %} ">
            Контакты
        </a>
    </div>
    <div class="nav-item">
        <a href="{% url 'basket:read' %}"
           class="nav-link {% if request.resolver_match.namespace == 'basket' %}
                  nav-link active
                  {% endif %} ">
            Корзина
        </a>
    </div>

        {% if request.user.is_authenticated %}
            <div class="nav-item">
                <a href="{% url 'auth:logout' %}"
                   class="nav-link {% if request.resolver_match.namespace == 'auth' %}
                          nav-link active
                          {% endif %} ">
                    Выйти
                </a>
            </div>
        {% else %}
            <div class="nav-item">
                <a href="{% url 'auth:login' %}"
                   class="nav-link {% if request.resolver_match.namespace == 'auth' %}
                          nav-link active
                          {% endif %} ">
                    Войти
                </a>
            </div>
        {% endif %}


</ul>