Django_Dr_Bug/Webshop/geekshop/authapp/urls.py
from django.urls import path

import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('register/', authapp.register, name='register'),
    path('login/', authapp.login, name='login'),
    path('edit/<int:pk>/', authapp.EditView.as_view(), name='edit'),
    path('logout/', authapp.logout, name='logout'),
]

Django_Dr_Bug/Webshop/geekshop/geekshop/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from mainapp import views as mainapp
from django.conf import settings
from django.conf.urls.static import static
if settings.DEBUG:
    import debug_toolbar

urlpatterns = [
    path('', mainapp.main, name='main'),
    path('products/', include('mainapp.urls', namespace='products')),  #mainapp.products, name='products'
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('contacts/', mainapp.contacts, name='contacts'),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('admin_custom/', include('adminapp.urls', namespace='admin_custom')),
    path('admin/', admin.site.urls),
    path('__debug__/', include(debug_toolbar.urls)),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Django_Dr_Bug/Webshop/geekshop/authapp/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class ShopUser(AbstractUser):
    class Meta:
        verbose_name = 'пользователь'
        verbose_name_plural = 'пользователи'

    avatar = models.ImageField(upload_to='users_avatars', blank=True)
    age = models.PositiveIntegerField(verbose_name='возраст')

    def __str__(self):
        return self.username

Django_Dr_Bug/Webshop/geekshop/authapp/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.forms import forms

from .models import ShopUser


class ShopUserRegisterForm(UserCreationForm):
    class Meta:
        model = ShopUser
        fields = ('username', 'first_name', 'password1', 'password2', 'email', 'age', 'avatar')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''

    def clean_age(self):
        print('Yeeee')
        data = self.cleaned_data['age']
        if data < 18:
            raise forms.ValidationError("Вы слишком молоды!")
        return data

Django_Dr_Bug/Webshop/geekshop/authapp/views.py
from django.shortcuts import render, HttpResponseRedirect
from django.views.generic.edit import UpdateView
from django.contrib import auth
from django.urls import reverse, reverse_lazy
from .forms import ShopUserRegisterForm
from .models import ShopUser

def register(request):
    if request.method == 'POST':
        register_form = ShopUserRegisterForm(request.POST, request.FILES)
        if register_form.is_valid():
            user = register_form.save()
            auth.login(request, user)
            return HttpResponseRedirect(reverse('main'))
    else:
        register_form = ShopUserRegisterForm()
    context = {'form': register_form}
    return render(request, 'authapp/register.html', context)

def login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        next = request.POST.get('next') if 'next' in request.GET.keys() else ''
        user = auth.authenticate(username=username, password=password)
        if user and user.is_active:
            auth.login(request, user)
            if next:
                return HttpResponseRedirect(next)
            else:
                return HttpResponseRedirect(reverse('main'))
    return render(request, 'authapp/login.html', {'title': 'Войти', 'next': request.GET.get('next')})

def logout(request):
    auth.logout(request)
    return HttpResponseRedirect(reverse('main'))

class EditView(UpdateView):
    model = ShopUser
    template_name = 'authapp/register.html'
    fields = 'username', 'email', 'avatar'
    success_url = reverse_lazy('main')

    def get_context_data(self, **kwargs):
        context = super(EditView, self).get_context_data(**kwargs)
        context['title'] = 'Редактирование профиля'
        context['submit_label'] = 'Применить'
        return context

Django_Dr_Bug/Webshop/geekshop/authapp/templates/authapp/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {{ title|title }}
    </title>
    {% block css %}
        <link rel="stylesheet" type="text/css" href="{% static 'mainapp/css/bootstrap.min.css' %}" >
        <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}" >
    {% endblock %}
    {% block js %}

    {% endblock %}
</head>
<body>
 <div class="container">
    <div class="login">
        {% block content %}

        {% endblock %}
    </div>
 </div>
</body>
</html>

Django_Dr_Bug/Webshop/geekshop/authapp/templates/authapp/login.html
{% extends 'authapp/base.html' %}
{% load staticfiles %}

{% block content %}
    <form class="form-horizontal" action="{% url 'auth:login' %}" method="POST">
        {% csrf_token %}
        <input class="form-control" name="username" placeholder="Имя пользователя"><br>
        <input class="form-control" name="password" placeholder="Пароль" type="password"><br>
        {% if next %}
            <input type="hidden" name="next" value="{{ next }}">
        {% endif %}
        <input class="form-control" type="submit" value="Войти">
    </form>
    {% if not request.user.is_authenticated %}
        <div class="nav-item">
            <a href="{% url 'auth:register' %}"
               class="nav-link {% if request.resolver_match.namespace == 'auth' %}
                      nav-link active
                      {% endif %} ">
                Зарегистрироваться?
            </a>
        </div>
    {% endif %}
{% endblock %}

Django_Dr_Bug/Webshop/geekshop/authapp/templates/authapp/register.html
{% extends 'authapp/base.html' %}
{% load staticfiles %}

{% block content %}
    <form class="form-horizontal" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <br>
        <input class="form-control" type="submit" value="зарегистрироваться">
    </form>
{% endblock %}