Django_Dr_Bug/Webshop/geekshop/adminapp/urls.py
from django.urls import path
import adminapp.views as adminapp

app_name = 'adminapp'

urlpatterns = [
    path('users/', adminapp.UserListView.as_view(), name='users'),
    path('users/create/', adminapp.UserCreateView.as_view(), name='user_create'),
    path('users/read/', adminapp.UserListView.as_view(), name='users'),
    path('users/read/superuser/<int:superuser_pk>/', adminapp.UserListView.as_view(), name='users_by_superusers'),
    path('users/read/<int:pk>/', adminapp.UserDetailView.as_view(), name='user_read'),
    path('users/update/<int:pk>/', adminapp.UserUpdateView.as_view(), name='user_update'),
    path('users/delete/<int:pk>/', adminapp.user_delete, name='user_delete'),
    path('categories/create/', adminapp.CategoryCreateView.as_view(), name='category_create'),
    path('categories/read/', adminapp.CategoryListView.as_view(), name='categories'),
    path('categories/update/<int:pk>/', adminapp.CategoryUpdateView.as_view(), name='category_update'),
    path('categories/delete/<int:pk>/', adminapp.CategoryDeleteView.as_view(), name='category_delete'),
    path('products/create/', adminapp.ProductCreateView.as_view(), name='product_create'),
    path('products/read/', adminapp.ProductListView.as_view(), name='products'),
    path('products/read/category/<int:category_pk>/', adminapp.ProductListView.as_view(), name='products_by_category'),
    path('products/read/<int:pk>/', adminapp.ProductDetailView.as_view(), name='product_read'),
    path('products/update/<int:pk>/', adminapp.ProductUpdateView.as_view(), name='product_update'),
    path('products/delete/<int:pk>/', adminapp.ProductDeleteView.as_view(), name='product_delete'),
]

#import adminapp.views as adminapp
#app_name = 'adminapp'

Django_Dr_Bug/Webshop/geekshop/authapp/urls.py
from django.urls import path

import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('register/', authapp.register, name='register'),
    path('login/', authapp.login, name='login'),
    path('edit/<int:pk>/', authapp.EditView.as_view(), name='edit'),
    path('logout/', authapp.logout, name='logout'),
]

Django_Dr_Bug/Webshop/geekshop/geekshop/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from mainapp import views as mainapp
from django.conf import settings
from django.conf.urls.static import static
if settings.DEBUG:
    import debug_toolbar

urlpatterns = [
    path('', mainapp.main, name='main'),
    path('products/', include('mainapp.urls', namespace='products')),  #mainapp.products, name='products'
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('contacts/', mainapp.contacts, name='contacts'),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('admin_custom/', include('adminapp.urls', namespace='admin_custom')),
    path('admin/', admin.site.urls),
    path('__debug__/', include(debug_toolbar.urls)),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Django_Dr_Bug/Webshop/geekshop/adminapp/models.py
from django.db import models

# Create your models here.

Django_Dr_Bug/Webshop/geekshop/adminapp/views.py
from django.contrib.auth.mixins import UserPassesTestMixin
from django.shortcuts import render, HttpResponseRedirect, get_object_or_404
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import DetailView
from django.views.generic.list import ListView
from mainapp.models import Product, ProductCategory
from authapp.models import ShopUser
#from .forms import ProductAdminForm

class IsSuperUserView(UserPassesTestMixin):
    def test_func(self):
        return self.request.user.is_superuser

class ProductListView(IsSuperUserView, ListView):
    model = Product
    template_name = 'adminapp/products.html'
    queryset = Product.objects.all()

    def get_queryset(self):
        queryset = super(ProductListView, self).get_queryset()
        if self.kwargs.get('category_pk'):
            queryset = queryset.filter(category=self.kwargs.get('category_pk'))
        return queryset

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(ProductListView, self).get_context_data(**kwargs)
        context['title'] = 'Все продукты. Админка'
        context['categories'] = ProductCategory.objects.all()
        return context

class ProductDetailView(IsSuperUserView, DetailView):
    model = Product
    template_name = 'adminapp/product.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(ProductDetailView, self).get_context_data(**kwargs)
        title = Product.objects.get(pk=self.kwargs.get('pk')).name
        context['title'] = '{}. Админка'.format(title)
        return context

class ProductCreateView(IsSuperUserView, CreateView):
    model = Product
    template_name = 'adminapp/product_update.html'
    success_url = reverse_lazy('admin_custom:products')
    fields = '__all__'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(ProductCreateView, self).get_context_data(**kwargs)
        context['title'] = 'Создание нового продукта. Админка'
        return context

class ProductDeleteView(IsSuperUserView, DeleteView):
    model = Product
    template_name = 'adminapp/product_delete.html'
    success_url = reverse_lazy('admin_custom:products')

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(ProductDeleteView, self).get_context_data(**kwargs)
        title = Product.objects.get(pk=self.kwargs.get('pk')).name
        context['title'] = 'Удаление {}. Админка'.format(title)
        return context

class ProductUpdateView(IsSuperUserView, UpdateView):
    model = Product
    template_name = 'adminapp/product_update.html'
    success_url = reverse_lazy('admin_custom:products')
    fields = '__all__'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(ProductUpdateView, self).get_context_data(**kwargs)
        title = Product.objects.get(pk=self.kwargs.get('pk')).name
        context['title'] = 'Изменение {}. Админка'.format(title)
        return context

    def get_success_url(self):
        return reverse_lazy('admin_custom:product_read', kwargs={'pk': self.kwargs.get('pk')})

class UserListView(IsSuperUserView, ListView):
    model = ShopUser
    template_name = 'adminapp/users.html'
    queryset = ShopUser.objects.all()

    def get_queryset(self):
        queryset = super(UserListView, self).get_queryset()
        is_superuser = self.request.GET.get('is_superuser')   #bool()
        if is_superuser == 'True':
            queryset = queryset.filter(is_superuser=True)
        elif is_superuser == 'False':
            queryset = queryset.filter(is_superuser=False)
        return queryset

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(UserListView, self).get_context_data(**kwargs)
        context['title'] = 'Все пользователи. Админка'
        context['superusers'] = ShopUser.objects.all()
        return context

class UserCreateView(IsSuperUserView, CreateView):
    model = ShopUser
    template_name = 'adminapp/product_update.html'
    success_url = reverse_lazy('admin_custom:users')
    fields = '__all__'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(UserCreateView, self).get_context_data(**kwargs)
        context['title'] = 'Создание нового пользователя. Админка'
        return context

class UserDetailView(IsSuperUserView, DetailView):
    model = ShopUser
    template_name = 'adminapp/user.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(UserDetailView, self).get_context_data(**kwargs)
        title = ShopUser.objects.get(pk=self.kwargs.get('pk')).username
        context['title'] = '{}. Админка'.format(title)
        return context

class UserUpdateView(IsSuperUserView, UpdateView):
    model = ShopUser
    template_name = 'adminapp/product_update.html'
    success_url = reverse_lazy('admin_custom:users')
    fields = '__all__'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(UserUpdateView, self).get_context_data(**kwargs)
        title = ShopUser.objects.get(pk=self.kwargs.get('pk')).username
        context['title'] = 'Изменение {}. Админка'.format(title)
        return context

    def get_success_url(self):
        return reverse_lazy('admin_custom:user_read', kwargs={'pk': self.kwargs.get('pk')})

def user_delete(request, pk=None):
    user = get_object_or_404(ShopUser, pk=pk)
    user.is_active = False
    user.save()
    return render(request, 'adminapp/users.html')

class CategoryListView(IsSuperUserView, ListView):
    model = ProductCategory
    template_name = 'adminapp/categories.html'
    queryset = ProductCategory.objects.all()

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(CategoryListView, self).get_context_data(**kwargs)
        context['title'] = 'Категории. Админка'
        return context

class CategoryCreateView(IsSuperUserView, CreateView):
    model = ProductCategory
    template_name = 'adminapp/product_update.html'
    success_url = reverse_lazy('admin_custom:categories')
    fields = '__all__'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(CategoryCreateView, self).get_context_data(**kwargs)
        context['title'] = 'Создание новой категорий. Админка'
        return context

class CategoryUpdateView(IsSuperUserView, UpdateView):
    model = ProductCategory
    template_name = 'adminapp/product_update.html'
    success_url = reverse_lazy('admin_custom:categories')
    fields = '__all__'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(CategoryUpdateView, self).get_context_data(**kwargs)
        title = ProductCategory.objects.get(pk=self.kwargs.get('pk')).name
        context['title'] = 'Изменение {}. Админка'.format(title)
        return context

class CategoryDeleteView(IsSuperUserView, DeleteView):
    model = ProductCategory
    template_name = 'adminapp/product_delete.html'
    success_url = reverse_lazy('admin_custom:categories')

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(CategoryDeleteView, self).get_context_data(**kwargs)
        title = ProductCategory.objects.get(pk=self.kwargs.get('pk')).name
        context['title'] = 'Удаление {}. Админка'.format(title)
        return context

Django_Dr_Bug/Webshop/geekshop/adminapp/templates/adminapp/categories.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ title }}</title>
</head>
<body>
<h2>Категории</h2>

<a href="{% url 'admin_custom:category_create' %}">Создать новую категорию</a>
<ul>
{% for object in object_list %}
    <li>
        {{ object.name|title }}
        <a href="{% url 'admin_custom:category_update' object.pk %}">Редактировать</a>
        <a href="{% url 'admin_custom:category_delete' object.pk %}">Удалить</a>
    </li>
{% endfor %}
</ul>
</body>
</html>

Django_Dr_Bug/Webshop/geekshop/adminapp/templates/adminapp/product.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ title }}</title>
</head>
<body>
    <h1>{{ object.name }}</h1>
    <img width="200" src='/media/{{ object.image }}/'>
    <p>{{ object.short_desc }}</p>
    <a href="{% url 'admin_custom:product_update' object.pk %}">Редактировать</a>
    <br>
    <a href="{% url 'admin_custom:product_delete' object.pk %}">Удалить</a>
    <br>
    <br>
    <a href="{% url 'admin_custom:products' %}"> <-- Ко всем продуктам</a>
</body>
</html>

Django_Dr_Bug/Webshop/geekshop/adminapp/templates/adminapp/product_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ title }}</title>
</head>
<body>
<div class="user_delete">
    Уверены, что хотите удалить {{ object.name }}?
    <form method="post">
      {% csrf_token %}
      <input class="btn btn-danger" type="submit" value="удалить">
    </form>
    <button class="btn btn-success">
      <a href="{% url 'admin_custom:products' %}">
        Отмена
      </a>
    </button>
  </div>
</body>
</html>

Django_Dr_Bug/Webshop/geekshop/adminapp/templates/adminapp/product_update.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ title }}</title>
</head>
<body>
<form class="form-horizontal" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Применить">
</form>
</body>
</html>

Django_Dr_Bug/Webshop/geekshop/adminapp/templates/adminapp/products.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ title }}</title>
</head>
<body>
<h2>Категории</h2>
{% include 'adminapp/includes/inc_category_menu.html' %}
<h2>Продукты</h2>
<a href="{% url 'admin_custom:product_create' %}">Создать новый продукт</a>
<ul>
{% for object in object_list %}
    <li>
        <a href="{% url 'admin_custom:product_read' object.pk %}">{{ object.name }}</a>
    </li>
{% endfor %}
</ul>
</body>
</html>

Django_Dr_Bug/Webshop/geekshop/adminapp/templates/adminapp/user.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ title }}</title>
</head>
<body>
    <h1>{{ object.username }}</h1>
    <img width="200" src='/media/{{ object.image }}/'>
    <p>Активный: {{ object.is_active }}</p>
    <p> ID {{ object.pk }} </p>
    <a href="{% url 'admin_custom:user_update' object.pk %}">Редактировать</a>
    <br>
    <a href="{% url 'admin_custom:user_delete' object.pk %}">Удалить</a>
    <br>
    <br>
    <a href="{% url 'admin_custom:users' %}"> <-- Ко всем пользователям</a>
</body>
</html>

Django_Dr_Bug/Webshop/geekshop/adminapp/templates/adminapp/users.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ title }}</title>
</head>
<body>
<h2>Статус пользователя:</h2>
    {% include 'adminapp/includes/inc_superuser_menu.html' %}
<h2>Пользователи</h2>
<a href="{% url 'admin_custom:user_create' %}">Создать новый пользователя</a>
<ul>
{% for object in object_list %}
    <li>
        <a href="{% url 'admin_custom:user_read' object.pk %}">{{ object.username|title }}</a>
    </li>
{% endfor %}
</ul>
</body>
</html>